"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Sparkles, Zap, Lock, Wand2 } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ExampleChat } from "@/components/ExampleChat";
import { TONES } from "@/lib/tones";

export default function LandingPage() {
  return (
    <main className="relative">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div
          aria-hidden
          className="grid-bg pointer-events-none absolute inset-0 -z-10"
        />
        <div
          aria-hidden
          className="pointer-events-none absolute left-1/2 top-[-180px] -z-10 h-[420px] w-[820px] -translate-x-1/2 rounded-full opacity-50 blur-3xl"
          style={{
            background:
              "radial-gradient(ellipse at center, rgba(139,92,246,0.45), transparent 70%)",
          }}
        />

        <div className="mx-auto max-w-6xl px-5 pt-12 pb-20 md:px-8 md:pt-20 md:pb-28">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            className="flex flex-col items-center text-center"
          >
            <span className="chip mb-6">
              <Sparkles size={13} className="text-fuchsia-300" />
              Powered by DeepSeek v3
            </span>

            <h1 className="text-balance text-4xl font-extrabold tracking-tight sm:text-5xl md:text-7xl">
              Reply <span className="gradient-text">smarter</span>
              <br className="hidden sm:block" /> with AI
            </h1>

            <p className="mx-auto mt-5 max-w-xl text-pretty text-base text-zinc-400 sm:text-lg">
              Generate perfect replies instantly — for Telegram, WhatsApp,
              Instagram, Tinder, email, and every dating app. Pick a tone, copy,
              done.
            </p>

            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.5 }}
              className="mt-8 flex flex-col items-center gap-3 sm:flex-row"
            >
              <Link href="/generator" className="btn-primary text-base">
                Try Free
                <ArrowRight size={18} />
              </Link>
              <Link href="#examples" className="btn-ghost text-base">
                See examples
              </Link>
            </motion.div>

            <p className="mt-4 text-xs text-zinc-500">
              No signup. Free model. Replies stay on your device.
            </p>
          </motion.div>

          {/* Tone chips preview */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35, duration: 0.6 }}
            className="mt-14 flex flex-wrap items-center justify-center gap-2"
          >
            {TONES.map((t) => (
              <span
                key={t.id}
                className="chip transition-transform hover:-translate-y-0.5"
              >
                <span aria-hidden>{t.emoji}</span>
                {t.label}
              </span>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Examples */}
      <section id="examples" className="relative">
        <div className="mx-auto max-w-6xl px-5 md:px-8">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mb-10 text-center"
          >
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              One message. <span className="gradient-text">Eight tones.</span>
            </h2>
            <p className="mt-3 text-zinc-400">
              Real examples generated by AI Reply.
            </p>
          </motion.div>

          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            <ExampleChat
              title="Alex"
              platform="Tinder · 23:14"
              emoji="🔥"
              delay={0}
              bubbles={[
                {
                  from: "them",
                  text: "Hey, what are you doing tonight?",
                },
                {
                  from: "you",
                  text: "Trying to figure out how to make tonight more interesting. Got any ideas? 😉",
                  tone: "💋 Flirty",
                },
              ]}
            />
            <ExampleChat
              title="Mom"
              platform="WhatsApp · 19:02"
              emoji="💚"
              delay={0.1}
              bubbles={[
                { from: "them", text: "Did you eat? You never call me." },
                {
                  from: "you",
                  text: "Just had dinner mom 🫶 calling you tomorrow after work — promise.",
                  tone: "🤝 Friendly",
                },
              ]}
            />
            <ExampleChat
              title="Hiring manager"
              platform="Email · 09:41"
              emoji="💼"
              delay={0.2}
              bubbles={[
                {
                  from: "them",
                  text: "Can you share your availability for an interview this week?",
                },
                {
                  from: "you",
                  text: "Thanks for reaching out. I'm available Wed 2–5pm or Thu morning — happy to work around your schedule.",
                  tone: "💼 Professional",
                },
              ]}
            />
            <ExampleChat
              title="Ex"
              platform="Instagram · 02:11"
              emoji="🧊"
              delay={0.05}
              bubbles={[
                { from: "them", text: "Hey stranger 👀 miss me?" },
                {
                  from: "you",
                  text: "Hey.",
                  tone: "🧊 Cold",
                },
              ]}
            />
            <ExampleChat
              title="Sam"
              platform="Telegram · 14:08"
              emoji="✈️"
              delay={0.15}
              bubbles={[
                {
                  from: "them",
                  text: "Bro the meeting just got moved to 5pm. Again.",
                },
                {
                  from: "you",
                  text: "If they move it one more time we're billing them by the reschedule.",
                  tone: "😂 Funny",
                },
              ]}
            />
            <ExampleChat
              title="Investor"
              platform="Email · 11:30"
              emoji="🧠"
              delay={0.25}
              bubbles={[
                {
                  from: "them",
                  text: "What's your plan for Q3 if growth doesn't pick up?",
                },
                {
                  from: "you",
                  text: "Cut burn 30%, double down on the two channels working, and push the launch to August. We'll have signal in 4 weeks either way.",
                  tone: "🧠 Smart CEO",
                },
              ]}
            />
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mt-20">
        <div className="mx-auto max-w-6xl px-5 md:px-8">
          <div className="grid gap-4 sm:grid-cols-3">
            {[
              {
                icon: Zap,
                title: "Instant",
                body: "Five replies in under three seconds — no waiting, no thinking.",
              },
              {
                icon: Wand2,
                title: "Sounds human",
                body: "Replies that match the platform — emoji, slang, length and all.",
              },
              {
                icon: Lock,
                title: "Stays private",
                body: "Your messages never leave the AI request. History is stored locally.",
              },
            ].map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08, duration: 0.5 }}
                className="glass rounded-2xl p-5 transition-transform hover:-translate-y-0.5"
              >
                <f.icon size={20} className="mb-3 text-fuchsia-300" />
                <p className="font-semibold text-white">{f.title}</p>
                <p className="mt-1 text-sm text-zinc-400">{f.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="mt-24">
        <div className="mx-auto max-w-3xl px-5 md:px-8">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="glass-strong relative overflow-hidden rounded-3xl p-8 text-center sm:p-12"
          >
            <div
              aria-hidden
              className="pointer-events-none absolute inset-0 -z-10 opacity-50"
              style={{
                background:
                  "radial-gradient(ellipse at top, rgba(217,70,239,0.25), transparent 60%), radial-gradient(ellipse at bottom, rgba(34,211,238,0.16), transparent 65%)",
              }}
            />
            <h3 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Stop staring at the screen.
            </h3>
            <p className="mx-auto mt-3 max-w-md text-zinc-400">
              Paste the message. Pick a tone. Get five replies that actually
              sound like you.
            </p>
            <Link href="/generator" className="btn-primary mt-7 text-base">
              Try Free
              <ArrowRight size={18} />
            </Link>
          </motion.div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
